# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by separate
# terms of service, privacy policy, and support documentation.
name: 'DevSkim'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * 1'

jobs:
  devskim:
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write

    name: 'DevSkim'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Run DevSkim Analysis'
        uses: microsoft/DevSkim-Action@v1

      - name: 'Upload DevSkim Results'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: devskim-results.sarif
